### ISSUE TITLE
Create Angular directive: <pre> to auto-apply Highlight.js

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-common#116]
Carrying on from https://github.com/GoogleCloudPlatform/gcloud-common/pull/115#issuecomment-200984631

With Angular, we should overload the `<pre>` element so that any code within it is automatically syntax highlighted. This should apply to snippets from any source (examples, descriptions, Markdown guides, etc.).

Will hljs know what language to use for highlighting from its own global configuration or should we add this functionality in manually through our own app config?

**Comment by quartzmo** [comment]
In case it helps, here is an example of an `<pre>` element encoded in a gcloud-ruby JSON doc service description.

```html
... <pre><code class=\"language-ruby\">require \"gcloud\"\n\ngcloud = Gcloud.new\nstorage = gcloud.storage\n\nbucket = storage.bucket \"my-todo-app\"\n</code></pre> ...
```

I believe our markdown processing adds the `class=\"language-ruby\"`, but I'm not certain.

**Comment by quartzmo** [comment]
@stephenplusplus @callmehiphop Please note that this is now the only blocking issue for gcloud-ruby to ship docs on the new site. (I'm not sure the `enhancement` label is accurate.)

Since I have removed the Pygments highlighting from our JSON, our longer-form docs are back to looking like this:

![ruby_code_no_highlight](https://cloud.githubusercontent.com/assets/205445/14033684/d965d080-f1e1-11e5-9efc-df7f32ccb62e.png)

**Comment by stephenplusplus** [comment]
I don't think I'll be able to jump on this issue in the immediate future. Are you able to take this one?

**Comment by quartzmo** [comment]
@callmehiphop Can you do it tomorrow? Otherwise I can give it a try.

**Comment by callmehiphop** [comment]
Sure, I can take a go at it
