### ISSUE TITLE
What value do we set for the user-agent after the library rename?

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/gcloud-common#179]
Hey folks,

Now that the repos are mostly renamed (gcloud-python and gcloud-go are left) I was wondering what was the value that we set in the user-agent?

I'm noticing that for Go we use [gcloud-golang/0.1](https://github.com/GoogleCloudPlatform/gcloud-golang/blob/a7a5fa889fa54fa06763ac2b7b96df7020ea1fcc/internal/cloud.go#L25), and I was wondering what the other languages were doing? And if some of the languages changed to use google-cloud-{lang} instead?

Omar

@blowmage @quartzmo @callmehiphop @stephenplusplus @dhermes @dwsupplee @mziccard @jgeewax @broady

**Comment by jgeewax** [comment]
If we change this in our clients, we need to work with the internal teams so that they recognize the new prefix. I thought we had agreed that this just wasn't worth doing the work. Regardless, once we decide, internal needs to make (and push) their changes first, and then we can make ours.

Seems reasonable to me though that we'd use the standard format: `google-cloud-<lang>/<version>` (with `golang` for Go and `dotnet` for C#/.NET)

---

Note that Node does this with `var USER_AGENT = PKG.name + '/' + PKG.version;` (where `PKG = require('../package.json');`) (see https://github.com/GoogleCloudPlatform/google-cloud-node/blob/77c83a15cbd79933776820b06039815b43561336/packages/common/src/util.js#L44). Is this going to cause a problem ...? Will it not use `gcloud-node` today?

**Comment by dhermes** [comment]
It's very easy for us to change in Python. As a side-bar, would it be worth it for the backend teams if we put **more** info in the user-agent, like if the app is running in GAE / on GCE.

**Comment by omaray** [comment]
I'm fine either way - no preference for this one. And yeah, I had also noticed the code your point to for Node (which also prompted me to ask the question). Your call @jgeewax - I guess we just need to be consistent (and update internal teams if something changes).

**Comment by dwsupplee** [comment]
Our user agent is set [here](https://github.com/GoogleCloudPlatform/google-cloud-php/blob/532140eb82042d925026f7bcd44106ec80139433/src/RequestWrapper.php#L209) (ex. `gcloud 0.7.1`) and will be a quick change if we decide to convert things.

**Comment by mziccard** [comment]
Java's user agent is still set to `gcloud-java/<version>`.

**Comment by jgeewax** [comment]
OK -- I'm calling this a "not worth the time" issue. If someone has strong feelings later, please re-open.

@stephenplusplus / @callmehiphop : Can you confirm that we didn't change our user-agent string when we renamed the repo?

**Comment by stephenplusplus** [comment]
After modularizing, all of our requests are via modules, so the UA strings reflect which module originated the request:

`@google-cloud/{service}/{releaseVersion}`. Is changing `@google-cloud` to `gcloud-node` sufficient?

**Comment by jgeewax** [comment]
Yes. We should not have changed the user-agent string.... Can we put it back to starting with `gcloud-node` as it was before the refactoring?

**Comment by stephenplusplus** [comment]
So @google-cloud/storage 0.1.0 makes a request, what should the UA be?

**Comment by stephenplusplus** [comment]
Sorry, missed the `started with` part of your comment. So it would be `gcloud-node/storage 0.1.0`?

**Comment by jgeewax** [comment]
That should be fine.

What was it pre-name change? I assume gcloud-node/0.1.0 with no signal about storage?

**Comment by stephenplusplus** [comment]
Yeah, because the requests were coming from the `gcloud` module, that and the module version was all we gave. After splitting up, we include the service module's name and *its* version, since they might not be going through `gcloud` at all.

**Comment by Capstan** [comment]
Please do not change `User-Agent` strings to not conform to https://tools.ietf.org/html/rfc7231#section-5.5.3. Two slashes does not work. A space between the product and the version is incorrect and will be interpreted as two different products. If you want to build more data about the specific product, use the comment string. If you have two composed products, compose them with spaces:

`User-Agent: SuperTool/1.0b1 ("quoted because contains #$%&;()\\\"; qdtext") AwesomeSDK/2.1 (not quoted because safe; ctext) google-cloud-erlang/0.1a`

See additional EBNF at https://tools.ietf.org/html/rfc7230#section-3.2.6.

**Comment by stephenplusplus** [comment]
We could just do `gcloud-node-storage/0.1.0`?

**Comment by Capstan** [comment]
@stephenplusplus @jgeewax My suggested alternative would be to either have `gcloud-node/0.1.0 (storage)` or `gcloud-node-storage/0.1.0` depending on what you consider the product is. Sounds like the former is preferable, esp. for dynamically generated languages, but I leave it to you.

**Comment by stephenplusplus** [comment]
Sounds good, thanks. I'll let @jgeewax/@omaray make the call.

**Comment by blowmage** [comment]
The libraries google-cloud-ruby uses enforce separate application name and version values, so appending the user agent string with the service will be impossible for us. We can do the following:

app name: "gcloud-ruby/storage"
app vers: 0.20.1

app name: "gcloud-ruby(storage)"
app vers: 0.20.1

**Comment by dwsupplee** [comment]
Thanks for the reference @Capstan.

I will open a PR modifying our user-agent string in PHP to `gcloud/0.7.1` instead of `gcloud 0.7.1`. @jgeewax @omaray just let me know if we want it in.

**Comment by Capstan** [comment]
One could also consider emitting the data about the API being captured. Could be as as simple as `(storage/v1)`, or in say the Java maven case, since the code is generated separately from the client library in use, the full generated version e.g., `(storage/v1-rev71-1.22.0)`, so if we identified a critical bug (e.g., security-related) in client generation code we can see current users and inform them, either out-of-band through support, or in-band through [`Warning`](https://tools.ietf.org/html/rfc7234#section-5.5.7) headers, e.g., `Warning: 299 GoogleCloudStorage "See security advisory http://example.com; upgrade your client to v1-rev-71-1.22.0 before <date> after which Google Cloud Storage will stop accepting requests." "Tue, 06 Sep 2016 16:24:00 GMT"`
