### ISSUE TITLE
docs: where will each gcloud library put their docs JSON?

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-common#42]
Carrying on from https://github.com/GoogleCloudPlatform/gcloud-common/pull/34#issuecomment-162110726

The docs being pushed to each repo will happen automatically, so the task of building the docs that match your release pace will happen in your repo.

I think our Angular app will need to know where to look for a JSON file that serves as a "table of contents". That file would just define the versions available for your project, and possibly the name of the latest version:

```json
{
  "versions": [
    "v0.1.0",
    "v0.1.1"
  ],
  "latest": "v0.1.1"
}
```

Then if we place our JSON files inside of gh-pages/versions/__versioname__.json, the app would know where to load from.

Does this work?

**Comment by quartzmo** [comment]
@stephenplusplus I believe I understand now. #35 is about deploying changes to the Angular app and other site assets (html, css, etc) to each gcloud-* repo's gh-pages. This issue (#42) is to specify the location and format of JSON files dynamically processed by the Angular app in each gcloud-* repo's gh-pages branch.  When a gcloud-* project merges new JSON into its gh-pages branch, the Angular app (being dynamic) serves new content. Am I getting it?

**Comment by stephenplusplus** [comment]
Not only getting it, but I feel that I get it better now as a result of
your explanation :)

**Comment by quartzmo** [comment]
@stephenplusplus Ha! Thanks.

**Comment by callmehiphop** [comment]
This might be slightly annoying, but I think we'll want to have a version folder - e.g. `gh-pages/versions/v0.26.0/` (or something similar).

My rationale being that we may have to version additional files like authorization language specific markdown files. 

Also if we decide to use a manifest to build the side navigation (vs. letting the json hierarchy dictate that) we may choose to distribute the various services to their own files. (bigquery.json, logging.json, etc.). I could see a concatenated file growing to be quite massive with all the APIs we'll eventually support. So a separated approach might be a bit more friendly on the front-end side of things.

**Comment by blowmage** [comment]
We are now building the documentation JSON on gcloud-ruby. Right now only the master branch has the JSON, but we will have a JSON document for all upcoming releases.

The page we chose was `/versions/master.json`, and the releases will be `/versions/v0.7.0.json`.

You can see the most up-to-date JSON [here](http://googlecloudplatform.github.io/gcloud-ruby/versions/master.json).

**Comment by stephenplusplus** [comment]
@callmehiphop we probably have to make the call now if we want to split on services. Should we follow:

```
gh-pages/versions/v0.26.0/bigquery.json
```

?

**Comment by callmehiphop** [comment]
I'm cool with splitting services, it will probably push our release of this back a little bit though.

**Comment by stephenplusplus** [comment]
At least having the directory separation seems most important. Splitting the services would help the download size, so might as well split?

**Comment by quartzmo** [comment]
@callmehiphop @stephenplusplus Speaking of download size, did you notice the size of our [JSON file](http://googlecloudplatform.github.io/gcloud-ruby/versions/master.json) for all services? It's just over 500kb.

**Comment by callmehiphop** [comment]
Well, if we're going to discuss making smaller files maybe we should revisit the manifest idea brought up previously? I liked the idea of removing the pages array and just creating a JSON file per service/class and building the navigation out via manifest.json file.

**Comment by callmehiphop** [comment]
Probably worth mentioning also that if we separate the services into smaller files then that means we'll also need to capture the release in which each API was introduced.

**Comment by stephenplusplus** [comment]
Can you elaborate on that a bit?

**Comment by callmehiphop** [comment]
Sure!

I think a benefit to the ginormous file approach is that we don't really have to track whether or not an API was available for a specific version since we're using the actual documentation to dynamically build the navigation. Breaking them into individual files means we now have to keep track of what files are available for any given version.

Using the following example let's say gcloud-lang releases PubSub via v0.25.0 and BigQuery via v0.26.0.

```
versions/v0.26.0/bigquery.json
versions/v0.26.0/pubsub.json
versions/v0.25.0/pubsub.json
```

We can't read directories on the client, so we'll need additional data to tell us what services to display depending on what version is currently being looked at.

There are obviously a couple ways to do this, but let's just look at the [current gcloud-node way](https://github.com/GoogleCloudPlatform/gcloud-node/blob/gh-pages/components/docs/docs-values.js#L111). Here we maintain a list of versions that indicate to us what versions we should hide/show.

**Comment by callmehiphop** [comment]
I think the least complicated way would be to create some kind of `apis.json` in the version directory that just gave a list of the APIs available..

```json
[{
  "name": "BigQuery",
  "id": "bigquery"
}, {
  "name": PubSub",
  "id": "pubsub"
}]
```

**Comment by dhermes** [comment]
We've (`gcloud-python`) [discussed][1] and are still seriously considering decoupling each service as a separate library so that we can de-couple releases, reduce the testing load, etc.

Thus, having a version for each service would be **necessary**.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/issues/1159

**Comment by stephenplusplus** [comment]
Thanks for the explanation. I like this idea as well. It should pay off
when we just need to build the navigation and not require a potentially
large download.

Will this file handle declaring custom pages as well, such as supplementary
Markdown content?

**Comment by callmehiphop** [comment]
@dhermes I don't think it's a question of having a version for each service, but rather do we lump all the services together into a giant JSON file (per version) or create a version directory with all the services in their own files.

e.g.

```
versions/v0.25.0.json
versions/v0.26.0.json
```

vs. 

```
versions/v0.25.0/bigquery.json
versions/v0.26.0/bigquery.json
versions/v0.26.0/pubsub.json
```

@stephenplusplus I think so, I haven't really heard much back in regards to versioning custom markdown pages, but it makes sense to me.

I'm thinking we would have a main manifest file in the root that listed the available versions, then for each version listed, a corresponding folder containing an additional json file stating what markdown content and api services are available for that version.

e.g.

```
manifest.json // { versions: ["master", "v0.26.0", ...] }
versions/master/toc.json // { apis: [{ name: "BigQuery", id: "bigquery" }], getting_started: [{ name: "FAQ", id: "faq" }] }
versions/master/bigquery.json
versions/master/faq.md
```

**Comment by dhermes** [comment]
ISTM

```
versions/v0.25.0/bigquery.json
versions/v0.26.0/bigquery.json
versions/v0.26.0/pubsub.json
```

is more future proof, especially if we have generic `stable` (for code released to PyPI or `npm`) and `latest` for `HEAD` in the dev tree.

**Comment by blowmage** [comment]
Like gcloud-python, the gcloud-ruby team sees many advantages to releasing separate libraries. This would make the current versioning scheme much, much more difficult. Not every service would have the version number bumped at the same time. So instead of choosing a release number and then a service, you would likely choose a service and then look at the release number. e.g. instead of this:

```
versions/v0.25.0/bigquery.json
versions/v0.26.0/bigquery.json
```

We may be better off having something like this:

```
services/bigquery/v0.25.0.json
services/bigquery/v0.26.0.json
```

This does add complexity, so I can see rejecting independently versioned services.

**Comment by blowmage** [comment]
If independently versioned services are rejected, then I think there is an advantage to outputting a single, monolithic JSON file. Similar to what we are outputting not, but updated to include the following:

* All code objects (classes, module, methods, etc...)
* All page content (OVERVIEW, AUTHENTICATION, GETTING_STARTED, etc...)
* The desired side navigation

Once that JSON file has been created, it can be re-parsed and split up into separate files (manifest, navigation, toc, services, etc...). We can even re-parse the monolithic JSON files if we discover better ways to serve the content in the future.

**Comment by callmehiphop** [comment]
@blowmage I like the idea of the independently versioned services, but I think I'd prefer to do something like post launch. That way we can get this app out there and if we take a separate file approach it shouldn't be too terrible to add the logic to load the appropriate version after the fact.

**Comment by dhermes** [comment]
:+1: On that approach

**Comment by callmehiphop** [comment]
Since we're breaking up the services into their own files, does it also make sense to move the classes/modules/etc. into their own file?

e.g.
`services/bigquery/table/v0.27.0.json`
or
`versions/v0.27.0/bigquery/table.json`

Since I do not believe we'll be displaying JSON from the parent service (bigquery) within the sub page (table), I see no benefit in lumping them together.
