### ISSUE TITLE
Add title to Code Constructs JSON

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-common#82]
When a code construct is rendered in the angular app a title is generated by concatinating the service name and the page name. In gcloud-ruby we have several code constructs that are nested 4 layers deep, and so the title doesn't make sense. We would prfer the ability to show the full namespaced name of the code construct. We suggest adding `title` as an optional attribute so we can customize the display by providing data in the JSON.

**Comment by callmehiphop** [comment]
:+1:

**Comment by quartzmo** [comment]
PR #97 added support for using [optional `title` if present, otherwise preserve existing behavior](https://github.com/GoogleCloudPlatform/gcloud-common/blob/master/site/src/app/docs/docs.route.js#L146-L148), so closing as implemented.

All JSON docs for gcloud-ruby now have this title, although it is optional.
