### ISSUE TITLE
Make previewing docs easier

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-common#95]
While working on a PR for our libraries, it's often required to see the docs before you submit a PR. Now that we have the website living here in gcloud-common, it's not an ideal process to combine the site files here with the JSON files there.

We need a better way to quickly do that (and recommend doing that re: #67), making sure gcloud-common@master is being used.

**Comment by callmehiphop** [comment]
To clarify, is the the ask to automate copying JSON content into the gcloud-common/site?

**Comment by stephenplusplus** [comment]
I can't think of any quick solutions to this, so I'm only posting about the problem and hoping we can find the best solution.

I imagine it would involve copying JSON content into gcloud-common/site, but it's important that gcloud-common is pulled at the time the "preview" command is run, which would likely mean fetching it remotely.

Or to keep the separation, maybe we can run the site in a "debug mode", which uses a separate convention to find the manifest & JSON (e.g., port 8081)? We can just run a dummy server in our gcloud-* repo to make the files available to the common site running from `gulp serve`.

Ideas welcome!

**Comment by callmehiphop** [comment]
Because the location of content can vary from app to app, I think this may be the wrong place to tackle your issue. I think a preview command would be nice, but I'm of the opinion that it would be more appropriately placed within the individual gcloud-* repositories and not here.

If a library is already up and running, they could simply checkout the `gh-pages` branch and drop the latest JSON into the <kbd>master</kbd> directory. This would bypass the need for node/gulp/bower/etc and would be pretty easy to automate - we already do this in several [gcloud-node shell scripts](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/scripts/build.sh#L30).

**Comment by stephenplusplus** [comment]
> If a library is already up and running, they could simply checkout the gh-pages branch and drop the latest JSON into the master directory.

That's perfect and makes a lot of sense. I think you should mention that in #67 as that seems the most straightforward.

**Comment by callmehiphop** [comment]
@stephenplusplus PTAL https://github.com/callmehiphop/gcloud-common/commit/5c4c32edc2da6fb825b9d085858bc64f226c62b7

**Comment by stephenplusplus** [comment]
Looks awesome!
